/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import forms.frmAyuda;
import forms.frmCotizar;
import forms.frmEmpleados;
import forms.frmIngresoVehiculoTaller;
import forms.frmInventarioVehiculo;
import forms.frmMarca;
import forms.frmOrdenTrabajo;
import forms.frmPrecioporServicio;
import forms.frmPropietario;
import forms.frmProveedores;
import forms.frmVehiculo;
import forms.frmVehiculoTestMarca;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author alsan
 */
public class mainView extends javax.swing.JFrame {

    /**
     * Creates new form mainView
     */
    public mainView() {
        initComponents();
        this.setExtendedState(mainView.MAXIMIZED_BOTH);
        this.setTitle("Sistema gestión talleres L&P");
    }

    /* Metodo para cambiar el icono de la ventana.*/
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/car.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        adminMenu = new javax.swing.JMenu();
        mnuEmpleado = new javax.swing.JMenuItem();
        mnuPropietarios = new javax.swing.JMenuItem();
        mnuClientes = new javax.swing.JMenuItem();
        mnuProveedores = new javax.swing.JMenuItem();
        accionesMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        jmnMarcaVehiculo = new javax.swing.JMenuItem();
        mnuItemMaestros = new javax.swing.JMenu();
        mnuPreciosServicios = new javax.swing.JMenuItem();
        mnuItemCotizacion = new javax.swing.JMenuItem();
        mnuItemInventario = new javax.swing.JMenuItem();
        mnuVentas = new javax.swing.JMenu();
        mnuIteCotizacion = new javax.swing.JMenuItem();
        mnuIngresoTaller = new javax.swing.JMenuItem();
        mnuClientes1 = new javax.swing.JMenuItem();
        mnuProveedores1 = new javax.swing.JMenuItem();
        mnuItemReportes = new javax.swing.JMenu();
        mnuPreciosServicios1 = new javax.swing.JMenuItem();
        mnuItemCotizacion1 = new javax.swing.JMenuItem();
        mnuItemInventario1 = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        mnuItemContenido = new javax.swing.JMenuItem();
        aboutMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        mainPane.setBackground(new java.awt.Color(255, 255, 255));

        fileMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        fileMenu.setMnemonic('f');
        fileMenu.setText("Archivo");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/small/logout.png"))); // NOI18N
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        adminMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/providers.png"))); // NOI18N
        adminMenu.setMnemonic('e');
        adminMenu.setText("Administración");

        mnuEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trabajadores.png"))); // NOI18N
        mnuEmpleado.setMnemonic('t');
        mnuEmpleado.setText("Empleados");
        mnuEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuEmpleadoMouseClicked(evt);
            }
        });
        mnuEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEmpleadoActionPerformed(evt);
            }
        });
        adminMenu.add(mnuEmpleado);

        mnuPropietarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clientes.png"))); // NOI18N
        mnuPropietarios.setMnemonic('y');
        mnuPropietarios.setText("Propietarios");
        mnuPropietarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPropietariosActionPerformed(evt);
            }
        });
        adminMenu.add(mnuPropietarios);

        mnuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clientes.png"))); // NOI18N
        mnuClientes.setMnemonic('y');
        mnuClientes.setText("Clientes");
        mnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClientesActionPerformed(evt);
            }
        });
        adminMenu.add(mnuClientes);

        mnuProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/proveedores.png"))); // NOI18N
        mnuProveedores.setMnemonic('p');
        mnuProveedores.setText("Proveedores");
        mnuProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProveedoresActionPerformed(evt);
            }
        });
        adminMenu.add(mnuProveedores);

        menuBar.add(adminMenu);

        accionesMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/car.png"))); // NOI18N
        accionesMenu.setMnemonic('h');
        accionesMenu.setText("Vehículos");

        contentMenuItem.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        contentMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/car_item.png"))); // NOI18N
        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Vehículo");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        accionesMenu.add(contentMenuItem);

        aboutMenuItem.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        aboutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/checklist.png"))); // NOI18N
        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Orden trabajo");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        accionesMenu.add(aboutMenuItem);

        jmnMarcaVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/implementation.png"))); // NOI18N
        jmnMarcaVehiculo.setText("Reprocesos");
        jmnMarcaVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnMarcaVehiculoActionPerformed(evt);
            }
        });
        accionesMenu.add(jmnMarcaVehiculo);

        menuBar.add(accionesMenu);

        mnuItemMaestros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/working-time.png"))); // NOI18N
        mnuItemMaestros.setMnemonic('h');
        mnuItemMaestros.setText("Maestros");

        mnuPreciosServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/money.png"))); // NOI18N
        mnuPreciosServicios.setText("Precios servicios");
        mnuPreciosServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPreciosServiciosActionPerformed(evt);
            }
        });
        mnuItemMaestros.add(mnuPreciosServicios);

        mnuItemCotizacion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        mnuItemCotizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/business-data.png"))); // NOI18N
        mnuItemCotizacion.setMnemonic('a');
        mnuItemCotizacion.setText("Cotización");
        mnuItemCotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCotizacionActionPerformed(evt);
            }
        });
        mnuItemMaestros.add(mnuItemCotizacion);

        mnuItemInventario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        mnuItemInventario.setMnemonic('a');
        mnuItemInventario.setText("Inventario");
        mnuItemInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemInventarioActionPerformed(evt);
            }
        });
        mnuItemMaestros.add(mnuItemInventario);

        menuBar.add(mnuItemMaestros);

        mnuVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/providers.png"))); // NOI18N
        mnuVentas.setMnemonic('e');
        mnuVentas.setText("Ventas");

        mnuIteCotizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trabajadores.png"))); // NOI18N
        mnuIteCotizacion.setMnemonic('t');
        mnuIteCotizacion.setText("Cotización");
        mnuIteCotizacion.setActionCommand("Cotización");
        mnuIteCotizacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuIteCotizacionMouseClicked(evt);
            }
        });
        mnuIteCotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIteCotizacionActionPerformed(evt);
            }
        });
        mnuVentas.add(mnuIteCotizacion);

        mnuIngresoTaller.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clientes.png"))); // NOI18N
        mnuIngresoTaller.setMnemonic('y');
        mnuIngresoTaller.setText("Ingreso vehículo taller");
        mnuIngresoTaller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIngresoTallerActionPerformed(evt);
            }
        });
        mnuVentas.add(mnuIngresoTaller);

        mnuClientes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clientes.png"))); // NOI18N
        mnuClientes1.setMnemonic('y');
        mnuClientes1.setText("Clientes");
        mnuClientes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClientes1ActionPerformed(evt);
            }
        });
        mnuVentas.add(mnuClientes1);

        mnuProveedores1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/proveedores.png"))); // NOI18N
        mnuProveedores1.setMnemonic('p');
        mnuProveedores1.setText("Proveedores");
        mnuProveedores1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProveedores1ActionPerformed(evt);
            }
        });
        mnuVentas.add(mnuProveedores1);

        menuBar.add(mnuVentas);

        mnuItemReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/analytics.png"))); // NOI18N
        mnuItemReportes.setMnemonic('h');
        mnuItemReportes.setText("Reportes");

        mnuPreciosServicios1.setText("Precios servicios");
        mnuPreciosServicios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPreciosServicios1ActionPerformed(evt);
            }
        });
        mnuItemReportes.add(mnuPreciosServicios1);

        mnuItemCotizacion1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        mnuItemCotizacion1.setMnemonic('a');
        mnuItemCotizacion1.setText("Cotización");
        mnuItemCotizacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCotizacion1ActionPerformed(evt);
            }
        });
        mnuItemReportes.add(mnuItemCotizacion1);

        mnuItemInventario1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        mnuItemInventario1.setMnemonic('a');
        mnuItemInventario1.setText("Inventario");
        mnuItemInventario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemInventario1ActionPerformed(evt);
            }
        });
        mnuItemReportes.add(mnuItemInventario1);

        menuBar.add(mnuItemReportes);

        helpMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/help.png"))); // NOI18N
        helpMenu.setMnemonic('h');
        helpMenu.setText("Ayuda");

        mnuItemContenido.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        mnuItemContenido.setMnemonic('a');
        mnuItemContenido.setText("Contenido");
        mnuItemContenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemContenidoActionPerformed(evt);
            }
        });
        helpMenu.add(mnuItemContenido);

        aboutMenuItem2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        aboutMenuItem2.setMnemonic('a');
        aboutMenuItem2.setText("Términos y condiciones");
        aboutMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItem2ActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem2);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPane, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPane, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void mnuEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuEmpleadoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_mnuEmpleadoMouseClicked

    private void mnuEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEmpleadoActionPerformed
        // TODO add your handling code here:
        frmEmpleados form = new frmEmpleados();
        mainPane.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_mnuEmpleadoActionPerformed

    private void mnuPropietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPropietariosActionPerformed
        // TODO add your handling code here:
        frmPropietario form = new frmPropietario();
        mainPane.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_mnuPropietariosActionPerformed

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
        // TODO add your handling code here:
        frmVehiculoTestMarca form = new frmVehiculoTestMarca();
        mainPane.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_contentMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
        frmOrdenTrabajo form = new frmOrdenTrabajo();
        mainPane.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void jmnMarcaVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnMarcaVehiculoActionPerformed
        // TODO add your handling code here:
        frmMarca form = new frmMarca();
        mainPane.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_jmnMarcaVehiculoActionPerformed

    private void mnuItemContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemContenidoActionPerformed
        // TODO add your handling code here:
        frmAyuda form = new frmAyuda();
        mainPane.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_mnuItemContenidoActionPerformed

    private void aboutMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutMenuItem2ActionPerformed

    private void mnuPreciosServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPreciosServiciosActionPerformed
        // TODO add your handling code here:
        frmPrecioporServicio form = new frmPrecioporServicio();
        mainPane.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_mnuPreciosServiciosActionPerformed

    private void mnuItemCotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCotizacionActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_mnuItemCotizacionActionPerformed

    private void mnuProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProveedoresActionPerformed
        // TODO add your handling code here:
        frmProveedores form = new frmProveedores();
        mainPane.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_mnuProveedoresActionPerformed

    private void mnuItemInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemInventarioActionPerformed
        // TODO add your handling code here:
        frmInventarioVehiculo form = new frmInventarioVehiculo();
        mainPane.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_mnuItemInventarioActionPerformed

    private void mnuPreciosServicios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPreciosServicios1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuPreciosServicios1ActionPerformed

    private void mnuItemCotizacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCotizacion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuItemCotizacion1ActionPerformed

    private void mnuItemInventario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemInventario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuItemInventario1ActionPerformed

    private void mnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuClientesActionPerformed

    private void mnuIteCotizacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuIteCotizacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuIteCotizacionMouseClicked

    private void mnuIteCotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIteCotizacionActionPerformed
        // TODO add your handling code here:
        frmCotizar form = new frmCotizar();
        mainPane.add(form);
        form.toFront();
        form.setVisible(true);

    }//GEN-LAST:event_mnuIteCotizacionActionPerformed

    private void mnuIngresoTallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIngresoTallerActionPerformed
        // TODO add your handling code here:
        frmIngresoVehiculoTaller form = new frmIngresoVehiculoTaller();
        mainPane.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_mnuIngresoTallerActionPerformed

    private void mnuClientes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClientes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuClientes1ActionPerformed

    private void mnuProveedores1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProveedores1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuProveedores1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem aboutMenuItem2;
    private javax.swing.JMenu accionesMenu;
    private javax.swing.JMenu adminMenu;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem jmnMarcaVehiculo;
    public static javax.swing.JDesktopPane mainPane;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnuClientes;
    private javax.swing.JMenuItem mnuClientes1;
    private javax.swing.JMenuItem mnuEmpleado;
    private javax.swing.JMenuItem mnuIngresoTaller;
    private javax.swing.JMenuItem mnuIteCotizacion;
    private javax.swing.JMenuItem mnuItemContenido;
    private javax.swing.JMenuItem mnuItemCotizacion;
    private javax.swing.JMenuItem mnuItemCotizacion1;
    private javax.swing.JMenuItem mnuItemInventario;
    private javax.swing.JMenuItem mnuItemInventario1;
    private javax.swing.JMenu mnuItemMaestros;
    private javax.swing.JMenu mnuItemReportes;
    private javax.swing.JMenuItem mnuPreciosServicios;
    private javax.swing.JMenuItem mnuPreciosServicios1;
    private javax.swing.JMenuItem mnuPropietarios;
    private javax.swing.JMenuItem mnuProveedores;
    private javax.swing.JMenuItem mnuProveedores1;
    private javax.swing.JMenu mnuVentas;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
